// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login-google": {
            "get": {
                "description": "Google OAuth callback. Browser flow (no json param): 302 redirect to the web app. Swagger/Postman: set ` + "`" + `json=true` + "`" + ` (required below) for JSON + Set-Cookie ` + "`" + `_tokenKey` + "`" + ` with no redirect — then Authorize CookieAuth and call google-backup routes. Does not change browser behavior.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Login with Google (login-google)",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Must be true in Swagger/API clients (uses existing ?json= query on SendResponse)",
                        "name": "json",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fresh Google OAuth code (single-use)",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Set-Cookie: _tokenKey",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleOAuthJSONSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleOAuthJSONError"
                        }
                    }
                }
            }
        },
        "/auth/register-google": {
            "get": {
                "description": "Google OAuth signup callback. Success is always JSON. On error, browser gets 302; use ` + "`" + `json=true` + "`" + ` in Swagger/Postman for JSON errors (existing SendResponse behavior).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Register with Google (register-google)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fresh Google OAuth code (single-use)",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state (UTM / verifier payload)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "When true, inserts CRM lead in Zoho",
                        "name": "zoho-insert",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Set true in Swagger when testing error paths (avoids redirect)",
                        "name": "json",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Set-Cookie: _tokenKey",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupRegisterSuccess"
                        }
                    },
                    "500": {
                        "description": "When json=true on failed callback",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleOAuthJSONError"
                        }
                    }
                }
            }
        },
        "/buckets/usage-totals-for-reserved": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/buckets/usage-totals-for-reserved` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buckets-reserved-usage"
                ],
                "summary": "Reserved vault usage totals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/consoleapi.ReservedBucketUsageItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/dashboard/stats` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard stats cards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/consoleapi.DashboardStatsCardSwaggerResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/jobs": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/auto-sync/jobs` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "List Google Backup auto-sync jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional Backup-Tools filter",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `POST /api/v0/google-backup/auto-sync/jobs` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Create Google Backup auto-sync jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup-Tools sync type (default daily)",
                        "name": "sync_type",
                        "in": "query"
                    },
                    {
                        "description": "Job create request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.CreateGoogleBackupAutoSyncJobsSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/jobs/project": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `PUT /api/v0/google-backup/auto-sync/jobs/project` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Update Google Backup jobs by project",
                "parameters": [
                    {
                        "description": "Project-scoped update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.UpdateGoogleBackupAutoSyncJobsByProjectSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/jobs/{job_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/auto-sync/jobs/{job_id}` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Get Google Backup auto-sync job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/jobs/{job_id}/policy": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/auto-sync/jobs/{job_id}/policy` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Get Google Backup policy for job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/policy": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/auto-sync/policy` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "List Google Backup auto-sync policies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup-Tools credential ID",
                        "name": "credential_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Storj project ID (with google_email)",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Google account email (with project_id)",
                        "name": "google_email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/auto-sync/policy/{policy_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/auto-sync/policy/{policy_id}` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Get Google Backup auto-sync policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policy_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `PUT /api/v0/google-backup/auto-sync/policy/{policy_id}` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Update Google Backup auto-sync policy schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policy_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy schedule update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.UpdateGoogleBackupAutoSyncPolicySwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/connect": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `POST /api/v0/google-backup/connect` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Connect Google account for backup",
                "parameters": [
                    {
                        "description": "OAuth authorization code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupConnectSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupConnectSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/domain-users": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/google-backup/domain-users` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup"
                ],
                "summary": "Gmail corporate domain-users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Google account email (default: latest credential for user)",
                        "name": "google_email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupDomainUsersSwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google-auth": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google-auth. Call before restore-all or manual restore. Pass Google OAuth id_token or access_token as google_key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-auth"
                ],
                "summary": "Exchange Google token for Backup-Tools auth JWT",
                "parameters": [
                    {
                        "description": "Google OAuth token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupAuthSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupAuthSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google/gmail/insert-mail": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google/gmail/insert-mail (max 10 base64 vault keys). Requires POST /google-backup/google-auth first. Headers: Authorization, ACCESS_TOKEN (or body fields).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-manual"
                ],
                "summary": "Manual restore Gmail messages",
                "parameters": [
                    {
                        "description": "Vault keys (forwarded as JSON array to Backup-Tools)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupManualRestoreSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google/satellite-to-calendar": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google/satellite-to-calendar (max 10 base64 vault keys).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-manual"
                ],
                "summary": "Manual restore Google Calendar",
                "parameters": [
                    {
                        "description": "Vault keys",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupManualRestoreSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google/satellite-to-contacts": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google/satellite-to-contacts (max 10 base64 vault keys).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-manual"
                ],
                "summary": "Manual restore Google Contacts",
                "parameters": [
                    {
                        "description": "Vault keys",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupManualRestoreSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google/satellite-to-drive": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google/satellite-to-drive (max 10 base64 vault keys).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-manual"
                ],
                "summary": "Manual restore Google Drive",
                "parameters": [
                    {
                        "description": "Vault keys",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupManualRestoreSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/google/satellite-to-photos": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /google/satellite-to-photos (max 10 base64 vault keys).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-manual"
                ],
                "summary": "Manual restore Google Photos",
                "parameters": [
                    {
                        "description": "Vault keys",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupManualRestoreSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/all": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /restore/all. Requires google_auth JWT (from POST /google-backup/google-auth), storx_access_grant, and login_id matching the Google account. Worker picks up job within ~30s.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "Start restore-all job",
                "parameters": [
                    {
                        "description": "Restore-all request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consoleapi.GoogleBackupRestoreAllSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/job/{job_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools GET /restore/job/{job_id} (use after POST /restore/all while status is queued)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "Get restore job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restore job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Backup-Tools google-auth JWT",
                        "name": "X-Google-Auth",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/job/{job_id}/cancel": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools POST /restore/job/{job_id}/cancel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "Cancel restore job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restore job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Backup-Tools google-auth JWT",
                        "name": "X-Google-Auth",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/job/{job_id}/dead-items": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools GET /restore/job/{job_id}/dead-items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "List restore dead-letter items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restore job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Backup-Tools google-auth JWT",
                        "name": "X-Google-Auth",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/jobs": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools GET /restore/jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "List restore job history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Max jobs (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Backup-Tools google-auth JWT",
                        "name": "X-Google-Auth",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/google-backup/restore/live": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Proxies Backup-Tools GET /restore/live (running jobs only). Pass google_auth in X-Google-Auth header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-backup-restore-cron"
                ],
                "summary": "List active restore jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup-Tools google-auth JWT",
                        "name": "X-Google-Auth",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.BackupToolsJSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}/daily-usage": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "**Full route:** ` + "`" + `GET /api/v0/projects/{id}/daily-usage` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects-daily-usage"
                ],
                "summary": "Project daily storage and bandwidth usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Range start (Unix seconds)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Range end (Unix seconds)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.ProjectDailyUsageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/consoleapi.SwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "consoleapi.BackupToolsJSONResponse": {
            "type": "object",
            "additionalProperties": true
        },
        "consoleapi.CreateGoogleBackupAutoSyncJobsSwaggerRequest": {
            "type": "object",
            "required": [
                "interval",
                "services"
            ],
            "properties": {
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "billing@salestalker.com",
                        "support@salestalker.com"
                    ]
                },
                "interval": {
                    "type": "string",
                    "example": "6h"
                },
                "on": {
                    "type": "string",
                    "example": ""
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "gmail",
                        "drive"
                    ]
                }
            }
        },
        "consoleapi.DashboardButtonSwagger": {
            "type": "object",
            "properties": {
                "click": {
                    "type": "string",
                    "example": ""
                },
                "color": {
                    "type": "string",
                    "example": "#2563EB"
                },
                "link": {
                    "type": "string",
                    "example": "/billing"
                },
                "text": {
                    "type": "string",
                    "example": "Upgrade"
                },
                "textColor": {
                    "type": "string",
                    "example": "#FFFFFF"
                }
            }
        },
        "consoleapi.DashboardIconSwagger": {
            "type": "object",
            "properties": {
                "backgroundColor": {
                    "type": "string",
                    "example": "#E8F0FE"
                },
                "url": {
                    "type": "string",
                    "example": "/static/icons/protected-users.svg"
                }
            }
        },
        "consoleapi.DashboardStatsCardSwaggerResponse": {
            "type": "object",
            "properties": {
                "button": {
                    "$ref": "#/definitions/consoleapi.DashboardButtonSwagger"
                },
                "description": {
                    "type": "string",
                    "example": "Google accounts with backup enabled"
                },
                "icon": {
                    "$ref": "#/definitions/consoleapi.DashboardIconSwagger"
                },
                "status": {
                    "$ref": "#/definitions/consoleapi.DashboardStatusSwagger"
                },
                "title": {
                    "type": "string",
                    "example": "Protected Users"
                },
                "value_1": {
                    "type": "string",
                    "example": "124"
                },
                "value_1_label": {
                    "type": "string",
                    "example": ""
                },
                "value_2": {
                    "type": "string",
                    "example": "+2 this week"
                },
                "value_2_label": {
                    "type": "string",
                    "example": "growth_this_week"
                }
            }
        },
        "consoleapi.DashboardStatusSwagger": {
            "type": "object",
            "properties": {
                "backgroundColor": {
                    "type": "string",
                    "example": "#18DB351A"
                },
                "textColor": {
                    "type": "string",
                    "example": "#388E3C"
                },
                "value": {
                    "type": "string",
                    "example": "84% Used"
                }
            }
        },
        "consoleapi.GoogleBackupAuthSwaggerRequest": {
            "type": "object",
            "required": [
                "google_key"
            ],
            "properties": {
                "google_key": {
                    "type": "string",
                    "example": "\u003cGoogle OAuth id_token or access_token\u003e"
                }
            }
        },
        "consoleapi.GoogleBackupAuthSwaggerResponse": {
            "type": "object",
            "properties": {
                "google-auth": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                }
            }
        },
        "consoleapi.GoogleBackupConnectSwaggerRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "4/0AeanS..."
                }
            }
        },
        "consoleapi.GoogleBackupConnectSwaggerResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean",
                    "example": true
                },
                "google_email": {
                    "type": "string",
                    "example": "user@gmail.com"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "consoleapi.GoogleBackupDomainUsersSwaggerResponse": {
            "type": "object",
            "properties": {
                "google_backup": {
                    "type": "object"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "consoleapi.GoogleBackupManualRestoreSwaggerRequest": {
            "type": "object",
            "required": [
                "google_auth",
                "keys",
                "storx_access_grant"
            ],
            "properties": {
                "google_auth": {
                    "type": "string",
                    "example": "\u003cJWT from POST /google-backup/google-auth\u003e"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "dXNlckBnbWFpbC5jb20vcGF0aC9maWxl"
                    ]
                },
                "storx_access_grant": {
                    "type": "string",
                    "example": "\u003cstorx access grant\u003e"
                }
            }
        },
        "consoleapi.GoogleBackupRegisterSuccess": {
            "type": "object",
            "properties": {
                "google_backup": {
                    "type": "object"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "consoleapi.GoogleBackupRestoreAllSwaggerRequest": {
            "type": "object",
            "required": [
                "google_auth",
                "login_id",
                "service",
                "storx_access_grant"
            ],
            "properties": {
                "google_auth": {
                    "type": "string",
                    "example": "\u003cJWT from POST /google-backup/google-auth\u003e"
                },
                "login_id": {
                    "type": "string",
                    "example": "user@gmail.com"
                },
                "service": {
                    "type": "string",
                    "example": "drive"
                },
                "storx_access_grant": {
                    "type": "string",
                    "example": "\u003cstorx access grant\u003e"
                }
            }
        },
        "consoleapi.GoogleOAuthJSONError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error getting token from Google"
                },
                "redirect_url": {
                    "type": "string",
                    "example": "https://storx.io/login"
                }
            }
        },
        "consoleapi.GoogleOAuthJSONSuccess": {
            "type": "object",
            "properties": {
                "redirect_url": {
                    "type": "string",
                    "example": "https://storx.io/"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "consoleapi.ProjectDailyUsageResponse": {
            "type": "object",
            "properties": {
                "allocatedBandwidthUsage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consoleapi.ProjectUsageByDayItem"
                    }
                },
                "settledBandwidthUsage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consoleapi.ProjectUsageByDayItem"
                    }
                },
                "storageUsage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consoleapi.ProjectUsageByDayItem"
                    }
                }
            }
        },
        "consoleapi.ProjectUsageByDayItem": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2026-05-26T00:00:00Z"
                },
                "value": {
                    "type": "integer",
                    "example": 9007199254740992
                }
            }
        },
        "consoleapi.ReservedBucketUsageItem": {
            "type": "object",
            "properties": {
                "before": {
                    "type": "string",
                    "example": "2026-05-28T10:00:00Z"
                },
                "bucketName": {
                    "type": "string",
                    "example": "gmail"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "egress": {
                    "type": "number",
                    "example": 12.3
                },
                "location": {
                    "type": "string",
                    "example": "us-east-1"
                },
                "objectCount": {
                    "type": "integer",
                    "example": 124
                },
                "projectID": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000001"
                },
                "segmentCount": {
                    "type": "integer",
                    "example": 500
                },
                "since": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "storage": {
                    "type": "number",
                    "example": 210.5
                }
            }
        },
        "consoleapi.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "consoleapi.UpdateGoogleBackupAutoSyncJobsByProjectSwaggerRequest": {
            "type": "object",
            "required": [
                "google_email",
                "project_id"
            ],
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "code": {
                    "type": "string",
                    "example": ""
                },
                "google_email": {
                    "type": "string",
                    "example": "user@gmail.com"
                },
                "interval": {
                    "type": "string",
                    "example": "nightly"
                },
                "on": {
                    "type": "string",
                    "example": "12am"
                },
                "project_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "\u003cgoogle refresh token\u003e"
                },
                "storx_token": {
                    "type": "string",
                    "example": "\u003cstorx access grant\u003e"
                }
            }
        },
        "consoleapi.UpdateGoogleBackupAutoSyncPolicySwaggerRequest": {
            "type": "object",
            "required": [
                "interval"
            ],
            "properties": {
                "interval": {
                    "type": "string",
                    "example": "3h"
                },
                "on": {
                    "type": "string",
                    "example": ""
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "type": "apiKey",
            "name": "_tokenKey",
            "in": "cookie"
        }
    },
    "tags": [
        {
            "description": "Project management operations",
            "name": "projects"
        },
        {
            "description": "Storage \u0026 bandwidth trends: GET /api/v0/projects/{id}/daily-usage — daily storageUsage and settledBandwidthUsage (bytes per day) for charts",
            "name": "projects-daily-usage"
        },
        {
            "description": "Bucket management operations",
            "name": "buckets"
        },
        {
            "description": "Reserved integration vault usage: GET /api/v0/buckets/usage-totals-for-reserved — bucketName, storage (GB), objectCount per vault (Google Backup, Dropbox, etc.)",
            "name": "buckets-reserved-usage"
        },
        {
            "description": "API key management operations",
            "name": "api-keys"
        },
        {
            "description": "Payment and billing operations",
            "name": "payments"
        },
        {
            "description": "Analytics operations",
            "name": "analytics"
        },
        {
            "description": "Google Backup: GET /auth/register-google and GET /auth/login-google (Google OAuth only), plus auto-sync job proxy to Backup-Tools",
            "name": "google-backup"
        },
        {
            "description": "Google Backup authentication: POST /google-backup/google-auth (Backup-Tools google-auth JWT)",
            "name": "google-backup-auth"
        },
        {
            "description": "Google Backup manual restore: synchronous vault → Google (POST /google-backup/google/*, max 10 keys). Call POST /google-backup/google-auth first.",
            "name": "google-backup-restore-manual"
        },
        {
            "description": "Google Backup restore-all (async): Backup-Tools worker cron proxies (/restore/all, /restore/live, /restore/job/*)",
            "name": "google-backup-restore-cron"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v0",
	Schemes:          []string{},
	Title:            "StorX Monitor API",
	Description:      "API documentation for StorX Monitor server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
