{
 "title": "StorX Satellite Monitoring",
 "tags": [
  "storx",
  "satellite",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(visit_event_by_code) by (code, scope, name, path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Run Functions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(function_times[5m])) by (kind, scope, name, path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Execution Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(function_times[5m])) by (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(function{field!=\"\"}[5m])) by (field, scope, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backup Dahshboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backup Job Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_job_success", "legendFormat": "Successful Backups" },
    { "expr": "backup_job_failure", "legendFormat": "Failed Backups" }
   ]
  },
  {
   "title": "Total Keys Backed Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_job_total_keys", "legendFormat": "Total Keys Backed Up" }
   ]
  },
  {
   "title": "Total Successful Backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_job_success", "legendFormat": "Total Success" }
   ]
  },
  {
   "title": "Backup Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_cmd_service_created_successfully",
     "legendFormat": "Service Created"
    }
   ]
  },
  {
   "title": "Total Failed Backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_job_failure", "legendFormat": "Total Failures" }
   ]
  },
  {
   "title": "Backup Job Success/Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(backup_job_success[5m])", "legendFormat": "Backup Success Rate" },
    { "expr": "rate(backup_job_failure[5m])", "legendFormat": "Backup Failure Rate" }
   ]
  },
  {
   "title": "Database Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(backup_database_update_successes[5m])",
     "legendFormat": "DB Update Success"
    },
    {
     "expr": "rate(backup_database_update_failures[5m])",
     "legendFormat": "DB Update Failures"
    }
   ]
  },
  {
   "title": "Backup Process Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(backup_worker_process_failures[5m])",
     "legendFormat": "Process Failures"
    },
    {
     "expr": "rate(backup_worker_process_already_completed[5m])",
     "legendFormat": "Already Completed"
    },
    {
     "expr": "rate(backup_worker_process_not_completed[5m])",
     "legendFormat": "Not Completed"
    }
   ]
  },
  {
   "title": "Backup Share Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(web3auth_upload_backup_share_size_bytes[5m])",
     "legendFormat": "Backup Share Upload Size"
    },
    {
     "expr": "rate(web3auth_get_backup_share_size_bytes[5m])",
     "legendFormat": "Backup Share Download Size"
    }
   ]
  },
  { "title": "smart Contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Overall Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_add_staker_failures[5m]) + rate(smartcontract_push_reputation_failures[5m]) + rate(smartcontract_is_staker_failures[5m]) + rate(smartcontract_get_reputation_failures[5m]) + rate(smartcontract_upload_social_share_failures[5m]) + rate(smartcontract_update_social_share_failures[5m]) + rate(smartcontract_get_social_share_failures[5m]) + rate(smartcontract_get_paginated_keyvalues_failures[5m]) + rate(smartcontract_get_total_keys_failures[5m])) / sum(rate(smartcontract_add_staker_attempts[5m]) + rate(smartcontract_push_reputation_attempts[5m]) + rate(smartcontract_is_staker_attempts[5m]) + rate(smartcontract_get_reputation_attempts[5m]) + rate(smartcontract_upload_social_share_attempts[5m]) + rate(smartcontract_update_social_share_attempts[5m]) + rate(smartcontract_get_social_share_attempts[5m]) + rate(smartcontract_get_paginated_keyvalues_attempts[5m]) + rate(smartcontract_get_total_keys_attempts[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_add_staker_attempts[5m]) + rate(smartcontract_push_reputation_attempts[5m]) + rate(smartcontract_is_staker_attempts[5m]) + rate(smartcontract_get_reputation_attempts[5m]) + rate(smartcontract_upload_social_share_attempts[5m]) + rate(smartcontract_update_social_share_attempts[5m]) + rate(smartcontract_get_social_share_attempts[5m]) + rate(smartcontract_get_paginated_keyvalues_attempts[5m]) + rate(smartcontract_get_total_keys_attempts[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KeyValue Contract Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_upload_social_share_successes[5m]) + rate(smartcontract_update_social_share_successes[5m]) + rate(smartcontract_get_social_share_successes[5m]) + rate(smartcontract_get_paginated_keyvalues_successes[5m]) + rate(smartcontract_get_total_keys_successes[5m])) / sum(rate(smartcontract_upload_social_share_attempts[5m]) + rate(smartcontract_update_social_share_attempts[5m]) + rate(smartcontract_get_social_share_attempts[5m]) + rate(smartcontract_get_paginated_keyvalues_attempts[5m]) + rate(smartcontract_get_total_keys_attempts[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reputation Contract Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_add_staker_successes[5m]) + rate(smartcontract_push_reputation_successes[5m]) + rate(smartcontract_is_staker_successes[5m]) + rate(smartcontract_get_reputation_successes[5m])) / sum(rate(smartcontract_add_staker_attempts[5m]) + rate(smartcontract_push_reputation_attempts[5m]) + rate(smartcontract_is_staker_attempts[5m]) + rate(smartcontract_get_reputation_attempts[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smart Contract Overall Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_add_staker_successes[5m]) + rate(smartcontract_push_reputation_successes[5m]) + rate(smartcontract_is_staker_successes[5m]) + rate(smartcontract_get_reputation_successes[5m]) + rate(smartcontract_upload_social_share_successes[5m]) + rate(smartcontract_update_social_share_successes[5m]) + rate(smartcontract_get_social_share_successes[5m]) + rate(smartcontract_get_paginated_keyvalues_successes[5m]) + rate(smartcontract_get_total_keys_successes[5m])) / sum(rate(smartcontract_add_staker_attempts[5m]) + rate(smartcontract_push_reputation_attempts[5m]) + rate(smartcontract_is_staker_attempts[5m]) + rate(smartcontract_get_reputation_attempts[5m]) + rate(smartcontract_upload_social_share_attempts[5m]) + rate(smartcontract_update_social_share_attempts[5m]) + rate(smartcontract_get_social_share_attempts[5m]) + rate(smartcontract_get_paginated_keyvalues_attempts[5m]) + rate(smartcontract_get_total_keys_attempts[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Data Size per Upload",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 46 },
   "targets": [
    {
     "expr": "avg(smartcontract_upload_social_share_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Data Size per Update",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "avg(smartcontract_update_social_share_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Retrieved Data Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 46 },
   "targets": [
    {
     "expr": "avg(smartcontract_get_social_share_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Volume (bytes per second)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_upload_social_share_size[5m])) + sum(rate(smartcontract_update_social_share_size[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Keys in System",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 46 },
   "targets": [
    {
     "expr": "smartcontract_get_total_keys_value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reputation on Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg(smartcontract_add_staker_reputation_on_error)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(smartcontract_push_reputation_value_on_error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Reputation Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "avg(smartcontract_get_reputation_value)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(smartcontract_add_staker_reputation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(smartcontract_push_reputation_value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KeyValue Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_upload_social_share_attempts[5m]) + rate(smartcontract_update_social_share_attempts[5m]) + rate(smartcontract_get_social_share_attempts[5m]) + rate(smartcontract_get_paginated_keyvalues_attempts[5m]) + rate(smartcontract_get_total_keys_attempts[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smart Contract Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(backup_smartcontract_keyvalue_getpaginated_successes[5m])",
     "legendFormat": "Smart Contract Success"
    },
    {
     "expr": "rate(backup_smartcontract_keyvalue_getpaginated_failures[5m])",
     "legendFormat": "Smart Contract Failures"
    }
   ]
  },
  {
   "title": "File Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(backup_file_save_successes[5m])",
     "legendFormat": "File Save Success"
    },
    {
     "expr": "rate(backup_file_save_failures[5m])",
     "legendFormat": "File Save Failures"
    }
   ]
  },
  {
   "title": "Reputation Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(smartcontract_add_staker_attempts[5m]) + rate(smartcontract_push_reputation_attempts[5m]) + rate(smartcontract_is_staker_attempts[5m]) + rate(smartcontract_get_reputation_attempts[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}