{
 "title": "StorX Network Statistics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "satellite", "label": "Satellite", "query": { "query": "label_values(satellite)" } }
  ]
 },
 "panels": [
  { "title": "Overview (Calculated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accumulated Datausage over all Satellites",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(storj_stats_storage_free_capacity_estimate_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "segment_commit_encrypted_size{field=\"sum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost Segments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(remote_segments_lost{field=\"sum\"})"
    }
   ]
  },
  {
   "title": "avg Segmentsize",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "segment_commit_encrypted_size{field=\"sum\"} / object_commit_segments{field=\"sum\"}"
    }
   ]
  },
  {
   "title": "Active nodes (contacted last 4 hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodetallies_totalsum{field=\"count\"}"
    }
   ]
  },
  {
   "title": "Suspended Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stray_nodes_dq_count{field=\"value\"}"
    }
   ]
  },
  {
   "title": "Vetted Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"storagenodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unvetted nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(remote_segments_checked{field=\"count\"})"
    }
   ]
  },
  {
   "title": "Accumulated Datausage over all Satellites",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(storj_stats_storage_free_capacity_estimate_bytes)",
     "legendFormat": "free reported space"
    },
    {
     "expr": "sum(total_remote_bytes{field=\"sum\"})",
     "legendFormat": "stored customer Data"
    }
   ]
  },
  {
   "title": "Nodestatus over all Satellites (max)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{comm=\"storagenode\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(function{name=\"_nodestats_NodeStats_GetStats\",field=\"failures\"})",
     "legendFormat": "offline nodes"
    },
    { "legendFormat": "suspended" }
   ]
  },
  { "title": "per Satellite Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Registered Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "function{name=\"__users__Insert\",field=\"successes\"} "
    }
   ]
  },
  {
   "title": "Used Capacity EU1",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "segment_commit_encrypted_size{field=\"sum\"}",
     "legendFormat": "used capacity"
    },
    {
     "expr": "max(allocated_space) - segment_commit_encrypted_size{field=\"sum\"}",
     "legendFormat": "reported free capacity"
    }
   ]
  },
  {
   "title": "Saltlake Ingress (last 30 Days)",
   "type": "stat",
   "description": "number of bytes uploaded (ingress) to the network for the last 30 days",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "segment_commit_encrypted_size{field=\"sum\"}"
    }
   ]
  },
  {
   "title": "US1 Egress (last 30 Days)",
   "type": "stat",
   "description": "number of bytes downloaded (egress) from the network for the last 30 days",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(user_agents_transfer_stats{type=\"download\",field=\"total\"}[30d]))"
    }
   ]
  },
  { "title": "$satellite details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "satellite" },
  {
   "title": "Healthy Pieces $satellite (Median)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, checker_segment_health)"
    }
   ]
  },
  {
   "title": "Healthy Pieces $satellite (Min)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(checker_segment_health)" }
   ]
  },
  {
   "title": "Nodestats $satellite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{job=\"storagenodes\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(up{job=\"storagenodes\"} == 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(up{job=\"storagenodes\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Livestatus nodes $satellite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(up{job=\"storagenodes\"})",
     "legendFormat": "active nodes"
    },
    {
     "expr": "count(up{job=\"storagenodes\"} == 0)",
     "legendFormat": "offline nodes"
    },
    {
     "expr": "count(up{job=\"storagenodes\"})",
     "legendFormat": "suspended"
    }
   ]
  },
  {
   "title": "Healthy Pieces $satellite",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.5, checker_segment_health)",
     "legendFormat": "Median Healthy Pieces"
    },
    { "expr": "min(checker_segment_health)", "legendFormat": "Minimum Healthy Pieces" },
    { "expr": "max(checker_segment_health)", "legendFormat": "__auto" },
    { "expr": "checker_segment_total_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remotsegments $satellite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "object_commit_segments{field=\"sum\"}",
     "legendFormat": "Remote Segments"
    },
    { "expr": "remote_segments_lost", "legendFormat": "Lost Remote Segments" }
   ]
  },
  {
   "title": "Vettingstatus $satellite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{job=\"storagenodes\"})",
     "legendFormat": "vetted nodes"
    },
    { "expr": "count(suspension_score < 1)", "legendFormat": "unvetted nodes" },
    {
     "expr": "count(up{job=\"storagenodes\"} == 0)",
     "legendFormat": "__auto"
    },
    { "expr": "count(suspension_score == 1)", "legendFormat": "__auto" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "---\n[<img src=\"/home/dhaval/Desktop/STOR-X/storxweb/static/images/SidebarLogoWhite.svg\" alt=\"StorX Logo\" height=\"100\"/>](https://www.storx.io/)"
   }
  }
 ]
}